### ISSUE TITLE
Ethics consideration in data collection process

### ISSUE THREAD

**Issue by seb646** [cthierst/WAAR_Project_Datasheet#2]
When discussing ethics in the datasheet (Collection Process, Question 6), it may be important to note some of the ethical challenges faced by the researchers. Although there was no formal ethical review process (nor do I think one was required, as they did not collect the data themselves), they spoke of their work as "desk research" which comes with specific ethical benefits like "not directly rely[ing] on emotional labour from individuals who have experienced violence." They exchanged these ethical benefits for inexact measures: "women’s participation in rebel organizations are ultimately assessments of visibility in available sources, not exact measures." Might be worth looking into this a bit and adding it to the ethics question, since it seems like this was a purposeful choice taken by the researchers. 

See "Challenges for the WAAR project" in https://journals.sagepub.com/doi/10.1177/00223433221128340.

**Comment by cthierst** [comment]
You're so right, thank you for bringing this to my attention!
