### ISSUE TITLE
Narrowing the timeframe

### ISSUE THREAD

**Issue by seb646** [cthierst/WAAR_Project_Datasheet#3]
I'm not sure if this helps, but (possibly in response to Collection Process, Question 3) it looks like the project began in 2021:

- Drs. Loken and Matfess were awarded their APSA "Small Grant" in 2021 ([source](https://www.meredithloken.com/_files/ugd/fabddc_3f5bf60630514c9aa07c90a7fada7dc1.pdf), pg. 3)
- The domain for their website (waarproject.com) was registered on November 4, 2021 ([source](https://whois.domaintools.com/waarproject.com))
- The fellowship Dr. Matfess received from the United States Institute of Peace’s Peace Scholar Fellowship Program was for the 2020–2021 cycle ([source](https://journals.sagepub.com/doi/10.1177/00223433221128340), see "Funding").

**Comment by cthierst** [comment]
updated, thank you!!
