### ISSUE TITLE
Funding data

### ISSUE THREAD

**Issue by seb646** [cthierst/WAAR_Project_Datasheet#4]
I tried to look into how much the researchers received to complete this project (for Collection Process, Question 4):

- Dr. Loken was the primary recipient of the APSA Small Grant, and received approximately $1000 ([Dr. Loken's CV](https://www.meredithloken.com/_files/ugd/fabddc_3f5bf60630514c9aa07c90a7fada7dc1.pdf), pg. 3; [APSA Grant 2021](https://web.archive.org/web/20210407192629/https://connect.apsanet.org/s16/non-working/funding-opportunities/))
- Dr. Matfess was the primary recipient of the Peace Scholar Fellowship from the United States Institute of Peace, and received $20,000 in funding for this project ([source](https://static1.squarespace.com/static/607085c1b3cf18533b78e955/t/623489fd670896743cc6c637/1647610365283/Matfess_CV_2022+%281%29.pdf), pg. 4)

**Comment by cthierst** [comment]
Updated, thank you!
